### ISSUE TITLE
Using without decorators

### ISSUE THREAD

**Issue by beckmeindia** [orionsoft/react-linkedin-login#1]
Hey,
 I am using react-universal with es6 and webpack2 **without decorators** 

Could you provide an example against the same? The docs are very less to understand completely.

Would really appreciate if I could get a complete example for the same.

Thanks

**Comment by femesq** [comment]
Hi,

All you need to do is to bind the function on class' constructor:

```
export default class LoginWithLinkedin extends React.Component {

  static propTypes = {
  }

  constructor(props) {
    super(props);
    this.callbackLinkedIn = this.callbackLinkedIn.bind(this);
  }

  callbackLinkedIn ({code, redirectUri}) {
    // Login with linkedin
  }

  render () {
    return (
      <LinkedIn
        clientId='xxx'
        callback={this.callbackLinkedIn}
        className={styles.linkedin}
        text='LinkedIn' />
    )
  }
}
```

Hope that helps..
