### ISSUE TITLE
How to implement "Exchange Authorization Code for an Access Token" once I get "Authoriztion Code" 

### ISSUE THREAD

**Issue by chandan7193** [orionsoft/react-linkedin-login#4]
After I get an Authorization code from Linkedin button how will I get Access_Token from LinkedIn?

**Comment by debelopumento** [comment]
In LinkedIn's official documentation there are 4 steps to complete the authentication: https://developer.linkedin.com/docs/oauth2

This library helps you get through step2. You're on your own on step1, 3 and 4.

**Comment by chandan7193** [comment]
![linkedin permission](https://user-images.githubusercontent.com/22831737/30771844-da27cf1e-a06d-11e7-9017-246303b2a434.png)

I have done Step1 and Step2 but when I click on SignIn button it take me to "https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=81lrtbxpin7518&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2F&state=srvv17" link and show me message "The redirect_uri does not match the registered value".
But after decoding the uri I find its correct "http:localhost:3000"

**Comment by chandan7193** [comment]
I found the problem redirect_uri was not correct.
Thanks for the help...
