### ISSUE TITLE
Linked access token is always invalid

### ISSUE THREAD

**Issue by ShrawanLakhe** [orionsoft/react-linkedin-login#6]
When i click on Linkedin button to connect with oauth api, then the access code that i am receiving is not working when fetching user basic detail info. It is always invalid.

but if i get a token from linkedin oauth api testing platform https://apigee.com/console/linkedin
then it works. 

can you guide me to solve the issue?

**Comment by xceltripofficial** [comment]
my bad. works perfectly fine. Thank you

**Comment by ShrawanLakhe** [comment]
My bad. works perfectly fine. Thank you.
